#!/usr/bin/env bash
# Crazyrouter × Hermes Agent - One-Click Setup (Linux/macOS/WSL2)
# Usage: curl -fsSL https://raw.githubusercontent.com/xujfcn/hermes-crazyrouter/main/setup.sh | bash

set -e

HERMES_HOME="${HERMES_HOME:-$HOME/.hermes}"
BASE_URL="https://crazyrouter.com/v1"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
CYAN='\033[0;36m'
YELLOW='\033[1;33m'
GRAY='\033[0;90m'
NC='\033[0m'

echo ""
echo -e "${CYAN}  ╔══════════════════════════════════════════════╗${NC}"
echo -e "${CYAN}  ║   Crazyrouter × Hermes Agent Setup Script    ║${NC}"
echo -e "${CYAN}  ║   https://crazyrouter.com                    ║${NC}"
echo -e "${CYAN}  ╚══════════════════════════════════════════════╝${NC}"
echo ""

# Check Hermes
if ! command -v hermes &>/dev/null; then
    echo -e "  ${YELLOW}[!] Hermes Agent not found.${NC}"
    echo ""
    echo "  Install it first:"
    echo -e "  ${GREEN}curl -fsSL https://raw.githubusercontent.com/NousResearch/hermes-agent/main/scripts/install.sh | bash${NC}"
    echo ""
    read -rp "  Continue anyway? Config will be ready when you install. [Y/n] " cont
    [[ "$cont" == "n" || "$cont" == "N" ]] && exit 1
fi

# Create .hermes directory
mkdir -p "$HERMES_HOME"

# Step 1: API Key
echo -e "  ${NC}[1/3] Enter your Crazyrouter API Key${NC}"
echo -e "  ${GRAY}      Get one at: https://crazyrouter.com${NC}"
echo ""
read -rp "  API Key: " API_KEY

if [[ -z "$API_KEY" ]]; then
    echo -e "  ${RED}[!] API Key cannot be empty.${NC}"
    exit 1
fi

# Step 2: Model selection
echo ""
echo -e "  ${NC}[2/3] Choose your default model:${NC}"
echo ""
echo -e "  ${GRAY}  1) claude-opus-4-7         Anthropic Opus 4.7 - strongest${NC}"
echo -e "  ${GRAY}  2) gpt-5.4                 OpenAI GPT-5.4 - latest${NC}"
echo -e "  ${GRAY}  3) claude-sonnet-4         Anthropic Sonnet 4 - balanced${NC}"
echo -e "  ${GRAY}  4) gemini-2.5-pro          Google - long context${NC}"
echo -e "  ${GRAY}  5) deepseek-chat           DeepSeek - cheapest${NC}"
echo -e "  ${GRAY}  6) qwen-max                Alibaba - multilingual${NC}"
echo -e "  ${GRAY}  7) gpt-4o                  OpenAI GPT-4o - versatile${NC}"
echo -e "  ${GRAY}  8) Custom (enter manually)${NC}"
echo ""
read -rp "  Choice [1]: " MODEL_CHOICE

case "${MODEL_CHOICE:-1}" in
    1) MODEL="claude-opus-4-7" ;;
    2) MODEL="gpt-5.4" ;;
    3) MODEL="claude-sonnet-4" ;;
    4) MODEL="gemini-2.5-pro" ;;
    5) MODEL="deepseek-chat" ;;
    6) MODEL="qwen-max" ;;
    7) MODEL="gpt-4o" ;;
    8) read -rp "  Enter model name: " MODEL ;;
    *) MODEL="claude-opus-4-7" ;;
esac

[[ -z "$MODEL" ]] && MODEL="claude-opus-4-7"

# Step 3: Write config
echo ""
echo -e "  ${NC}[3/3] Writing configuration...${NC}"

ENV_FILE="$HERMES_HOME/.env"
CONFIG_FILE="$HERMES_HOME/config.yaml"

# Backup and update .env
if [[ -f "$ENV_FILE" ]]; then
    cp "$ENV_FILE" "$ENV_FILE.bak"
    echo -e "  ${GRAY}[*] Backed up .env → .env.bak${NC}"
    # Remove old entries
    grep -v "^OPENAI_API_KEY=" "$ENV_FILE" | grep -v "^OPENAI_BASE_URL=" > "$ENV_FILE.tmp" || true
    mv "$ENV_FILE.tmp" "$ENV_FILE"
fi

echo "OPENAI_API_KEY=$API_KEY" >> "$ENV_FILE"
echo "OPENAI_BASE_URL=$BASE_URL" >> "$ENV_FILE"
chmod 600 "$ENV_FILE"
echo -e "  ${GREEN}[OK] .env updated${NC}"

# Write config.yaml
CONFIG_CONTENT="# Crazyrouter configuration for Hermes Agent
# Generated by Crazyrouter setup script
# All 627+ models: https://crazyrouter.com

model:
  provider: \"custom\"
  default: \"$MODEL\"
  base_url: \"$BASE_URL\""

if [[ -f "$CONFIG_FILE" ]]; then
    cp "$CONFIG_FILE" "$CONFIG_FILE.bak"
    echo -e "  ${GRAY}[*] Backed up config.yaml → config.yaml.bak${NC}"
    echo ""
    echo -e "  ${YELLOW}[?] config.yaml already exists.${NC}"
    echo -e "  ${GRAY}    O = Overwrite with Crazyrouter config${NC}"
    echo -e "  ${GRAY}    K = Keep existing${NC}"
    read -rp "  Choice [O]: " OVERWRITE
    if [[ "$OVERWRITE" == "K" || "$OVERWRITE" == "k" ]]; then
        echo -e "  ${GRAY}[*] Keeping existing config.yaml${NC}"
    else
        echo "$CONFIG_CONTENT" > "$CONFIG_FILE"
        echo -e "  ${GREEN}[OK] config.yaml updated${NC}"
    fi
else
    echo "$CONFIG_CONTENT" > "$CONFIG_FILE"
    echo -e "  ${GREEN}[OK] config.yaml created${NC}"
fi

# Done
PADDED_MODEL=$(printf "%-33s" "$MODEL")
echo ""
echo -e "${GREEN}  ╔══════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}  ║            Setup Complete!                    ║${NC}"
echo -e "${GREEN}  ╠══════════════════════════════════════════════╣${NC}"
echo -e "${GREEN}  ║                                              ║${NC}"
echo -e "${GREEN}  ║  Provider:  Crazyrouter (custom)             ║${NC}"
echo -e "${GREEN}  ║  Base URL:  https://crazyrouter.com/v1       ║${NC}"
echo -e "${GREEN}  ║  Model:     ${PADDED_MODEL}║${NC}"
echo -e "${GREEN}  ║  Config:    ~/.hermes/                       ║${NC}"
echo -e "${GREEN}  ║                                              ║${NC}"
echo -e "${GREEN}  ║  Run 'hermes' to start chatting!             ║${NC}"
echo -e "${GREEN}  ║                                              ║${NC}"
echo -e "${GREEN}  ║  Switch models anytime:                      ║${NC}"
echo -e "${GREEN}  ║    /model gpt-4o                             ║${NC}"
echo -e "${GREEN}  ║    /model claude-sonnet-4                    ║${NC}"
echo -e "${GREEN}  ║    /model deepseek-chat                      ║${NC}"
echo -e "${GREEN}  ║                                              ║${NC}"
echo -e "${GREEN}  ║  627+ models via one API key                 ║${NC}"
echo -e "${GREEN}  ╚══════════════════════════════════════════════╝${NC}"
echo ""

# Optional connection test
read -rp "  Test the connection? [Y/n] " TEST
if [[ "$TEST" != "n" && "$TEST" != "N" ]]; then
    echo ""
    echo -e "  ${GRAY}[*] Testing API connection...${NC}"
    RESPONSE=$(curl -s -w "\n%{http_code}" -X POST "$BASE_URL/chat/completions" \
        -H "Authorization: Bearer $API_KEY" \
        -H "Content-Type: application/json" \
        -d "{\"model\":\"$MODEL\",\"messages\":[{\"role\":\"user\",\"content\":\"Say 'Crazyrouter connected!' in one line.\"}],\"max_tokens\":20}" \
        2>/dev/null) || true

    HTTP_CODE=$(echo "$RESPONSE" | tail -1)
    BODY=$(echo "$RESPONSE" | sed '$d')

    if [[ "$HTTP_CODE" == "200" ]]; then
        REPLY=$(echo "$BODY" | grep -o '"content":"[^"]*"' | head -1 | sed 's/"content":"//;s/"$//')
        echo -e "  ${GREEN}[OK] $REPLY${NC}"
    else
        echo -e "  ${RED}[!] Connection test failed (HTTP $HTTP_CODE)${NC}"
        echo -e "  ${YELLOW}[*] Check your API key and try again.${NC}"
    fi
fi

echo ""
