#!/bin/bash
# ============================================================
# Hermes Agent × Crazyrouter Setup Script
# Configure Hermes to use Crazyrouter as the inference provider
# ============================================================

set -e

HERMES_DIR="${HERMES_DIR:-$HOME/.hermes}"
ENV_FILE="$HERMES_DIR/.env"
CONFIG_FILE="$HERMES_DIR/config.yaml"

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
RED='\033[0;31m'
NC='\033[0m'

echo ""
echo -e "${CYAN}╔══════════════════════════════════════════════╗${NC}"
echo -e "${CYAN}║  Hermes Agent × Crazyrouter Setup            ║${NC}"
echo -e "${CYAN}║  One API key — 600+ AI models                ║${NC}"
echo -e "${CYAN}╚══════════════════════════════════════════════╝${NC}"
echo ""

# ── 1. Ensure ~/.hermes exists ─────────────────────────────
mkdir -p "$HERMES_DIR"

# ── 2. Prompt for API key ──────────────────────────────────
if [ -n "$CRAZYROUTER_API_KEY" ]; then
    API_KEY="$CRAZYROUTER_API_KEY"
    echo -e "${GREEN}✔ Using CRAZYROUTER_API_KEY from environment${NC}"
else
    echo -e "${YELLOW}Get your free API key at: https://crazyrouter.com${NC}"
    echo -n "Enter your Crazyrouter API key: "
    read -s API_KEY
    echo ""
fi

if [ -z "$API_KEY" ]; then
    echo -e "${RED}✗ API key is required. Exiting.${NC}"
    exit 1
fi

# ── 3. Write .env ──────────────────────────────────────────
echo -e "${CYAN}→ Writing $ENV_FILE${NC}"

# Preserve existing .env if it exists, just update/add relevant lines
if [ -f "$ENV_FILE" ]; then
    # Remove old openrouter/crazyrouter entries
    grep -v -E "^(OPENROUTER_API_KEY|OPENAI_API_KEY|OPENAI_BASE_URL|# Crazyrouter)" "$ENV_FILE" > "$ENV_FILE.tmp" || true
    mv "$ENV_FILE.tmp" "$ENV_FILE"
fi

cat >> "$ENV_FILE" << EOF

# Crazyrouter — OpenAI-compatible API gateway (600+ models)
# https://crazyrouter.com
OPENROUTER_API_KEY=$API_KEY
EOF

echo -e "${GREEN}✔ API key written to .env${NC}"

# ── 4. Write / patch config.yaml ──────────────────────────
echo -e "${CYAN}→ Configuring $CONFIG_FILE${NC}"

if [ ! -f "$CONFIG_FILE" ]; then
    # Fresh config — write minimal setup
    cat > "$CONFIG_FILE" << EOF
# Hermes Agent configuration — generated by setup-crazyrouter.sh
model:
  provider: "openrouter"
  base_url: "https://crazyrouter.com/v1"
  default: "anthropic/claude-opus-4.6"

compression:
  enabled: true
  threshold: 0.50
  summary_model: "google/gemini-flash-2.0"

terminal:
  backend: "local"
  cwd: "."
  timeout: 180

memory:
  memory_enabled: true
  user_profile_enabled: true
EOF
    echo -e "${GREEN}✔ Created new config.yaml${NC}"
else
    # Patch existing config — update model section
    python3 - << 'PY'
import re, sys

config_file = "$CONFIG_FILE"

with open(config_file, "r") as f:
    content = f.read()

# Update base_url
content = re.sub(
    r'(base_url:\s*")[^"]*(")',
    r'\1https://crazyrouter.com/v1\2',
    content
)

# Update provider
content = re.sub(
    r'(provider:\s*")[^"]*(")',
    r'\1openrouter\2',
    content
)

# If base_url not found, inject into model section
if 'base_url' not in content:
    content = re.sub(
        r'(model:\s*\n)',
        r'\1  provider: "openrouter"\n  base_url: "https://crazyrouter.com/v1"\n',
        content
    )

with open(config_file, "w") as f:
    f.write(content)

print("config.yaml updated")
PY
    echo -e "${GREEN}✔ Updated existing config.yaml${NC}"
fi

# ── 5. Summary ─────────────────────────────────────────────
echo ""
echo -e "${GREEN}══════════════════════════════════════════════${NC}"
echo -e "${GREEN}  Setup complete!${NC}"
echo -e "${GREEN}══════════════════════════════════════════════${NC}"
echo ""
echo -e "  Provider : ${CYAN}Crazyrouter${NC} (OpenRouter-compatible)"
echo -e "  Base URL : ${CYAN}https://crazyrouter.com/v1${NC}"
echo -e "  API Key  : ${CYAN}${API_KEY:0:8}...${NC}"
echo ""
echo -e "${YELLOW}Default model: anthropic/claude-opus-4.6${NC}"
echo -e "${YELLOW}To change:     hermes model${NC}"
echo ""
echo -e "Popular models via Crazyrouter:"
echo -e "  • anthropic/claude-opus-4.6        (best reasoning)"
echo -e "  • anthropic/claude-sonnet-4-5      (balanced)"
echo -e "  • openai/gpt-5.2                   (OpenAI flagship)"
echo -e "  • google/gemini-3-pro              (multimodal)"
echo -e "  • deepseek/deepseek-r2             (budget reasoning)"
echo ""
echo -e "Start Hermes:"
echo -e "  ${CYAN}hermes${NC}              — interactive CLI"
echo -e "  ${CYAN}hermes chat${NC}         — chat mode"
echo ""
echo -e "Manage models:"
echo -e "  ${CYAN}hermes model${NC}        — switch models interactively"
echo -e "  ${CYAN}hermes model list${NC}   — list all available models"
echo ""
echo -e "Documentation: ${CYAN}https://crazyrouter.com/docs${NC}"
echo ""
