@echo off
chcp 65001 >nul 2>&1
setlocal EnableDelayedExpansion

echo.
echo  ╔══════════════════════════════════════════════╗
echo  ║   Crazyrouter × Hermes Agent Setup Script    ║
echo  ║   https://crazyrouter.com                    ║
echo  ╚══════════════════════════════════════════════╝
echo.

:: Check if Hermes is installed
where hermes >nul 2>&1
if %errorlevel% neq 0 (
    echo  [!] Hermes Agent not found. Installing...
    echo.
    echo  Please install Hermes first:
    echo  https://github.com/nousresearch/hermes-agent
    echo.
    echo  Run in WSL2:
    echo  curl -fsSL https://raw.githubusercontent.com/NousResearch/hermes-agent/main/scripts/install.sh ^| bash
    echo.
    pause
    exit /b 1
)

:: Set Hermes home directory
set "HERMES_HOME=%USERPROFILE%\.hermes"

:: Create directory if not exists
if not exist "%HERMES_HOME%" (
    echo  [*] Creating %HERMES_HOME% ...
    mkdir "%HERMES_HOME%"
)

:: Prompt for API Key
echo  [1/3] Enter your Crazyrouter API Key
echo        (Get one at https://crazyrouter.com)
echo.
set /p "API_KEY=  API Key: "

if "%API_KEY%"=="" (
    echo.
    echo  [!] API Key cannot be empty. Exiting.
    pause
    exit /b 1
)

:: Prompt for model selection
echo.
echo  [2/3] Choose your default model:
echo.
echo    1) claude-opus-4-7      (Anthropic, strongest)
echo    2) gpt-5.4              (OpenAI, latest)
echo    3) claude-sonnet-4.6    (Anthropic, balanced)
echo    4) gemini-3.1-pro       (Google)
echo    5) deepseek-chat        (DeepSeek, cheapest)
echo    6) qwen-max             (Alibaba)
echo    7) gpt-4o               (OpenAI, versatile)
echo    8) Custom (enter manually)
echo.
set /p "MODEL_CHOICE=  Choice [1]: "

if "%MODEL_CHOICE%"=="" set "MODEL_CHOICE=1"
if "%MODEL_CHOICE%"=="1" set "MODEL=claude-opus-4-7"
if "%MODEL_CHOICE%"=="2" set "MODEL=gpt-5.4"
if "%MODEL_CHOICE%"=="3" set "MODEL=claude-sonnet-4.6"
if "%MODEL_CHOICE%"=="4" set "MODEL=gemini-3.1-pro"
if "%MODEL_CHOICE%"=="5" set "MODEL=deepseek-chat"
if "%MODEL_CHOICE%"=="6" set "MODEL=qwen-max"
if "%MODEL_CHOICE%"=="7" set "MODEL=gpt-4o"
if "%MODEL_CHOICE%"=="8" (
    set /p "MODEL=  Enter model name: "
)

if "%MODEL%"=="" set "MODEL=claude-opus-4-7"

:: Write .env file
echo.
echo  [3/3] Writing configuration...
echo.

:: Backup existing .env if present
if exist "%HERMES_HOME%\.env" (
    echo  [*] Backing up existing .env to .env.bak
    copy /y "%HERMES_HOME%\.env" "%HERMES_HOME%\.env.bak" >nul
)

:: Check if keys already exist in .env, append or create
if exist "%HERMES_HOME%\.env" (
    :: Remove old Crazyrouter entries if any
    findstr /v /i "OPENAI_API_KEY OPENAI_BASE_URL" "%HERMES_HOME%\.env" > "%HERMES_HOME%\.env.tmp" 2>nul
    move /y "%HERMES_HOME%\.env.tmp" "%HERMES_HOME%\.env" >nul
)

>> "%HERMES_HOME%\.env" echo OPENAI_API_KEY=%API_KEY%
>> "%HERMES_HOME%\.env" echo OPENAI_BASE_URL=https://crazyrouter.com/v1

echo  [OK] .env updated

:: Write or update config.yaml
if exist "%HERMES_HOME%\config.yaml" (
    echo  [*] Backing up existing config.yaml to config.yaml.bak
    copy /y "%HERMES_HOME%\config.yaml" "%HERMES_HOME%\config.yaml.bak" >nul
)

:: Create minimal config.yaml with Crazyrouter settings
> "%HERMES_HOME%\config.yaml.cr" (
    echo # Crazyrouter configuration for Hermes Agent
    echo # Generated by Crazyrouter setup script
    echo # Docs: https://crazyrouter.com
    echo.
    echo model:
    echo   provider: "custom"
    echo   default: "%MODEL%"
    echo   base_url: "https://crazyrouter.com/v1"
)

:: If config.yaml exists, ask whether to overwrite or merge
if exist "%HERMES_HOME%\config.yaml" (
    echo.
    echo  [?] config.yaml already exists.
    echo      O = Overwrite model section only
    echo      K = Keep existing, skip
    set /p "OVERWRITE=  Choice [O]: "
    if /i "!OVERWRITE!"=="K" (
        echo  [*] Keeping existing config.yaml
        del "%HERMES_HOME%\config.yaml.cr" >nul
    ) else (
        move /y "%HERMES_HOME%\config.yaml.cr" "%HERMES_HOME%\config.yaml" >nul
        echo  [OK] config.yaml updated
    )
) else (
    move /y "%HERMES_HOME%\config.yaml.cr" "%HERMES_HOME%\config.yaml" >nul
    echo  [OK] config.yaml created
)

:: Done
echo.
echo  ╔══════════════════════════════════════════════╗
echo  ║            Setup Complete!                    ║
echo  ╠══════════════════════════════════════════════╣
echo  ║                                              ║
echo  ║  Provider:  Crazyrouter (custom)             ║
echo  ║  Base URL:  https://crazyrouter.com/v1       ║
echo  ║  Model:     %MODEL%
echo  ║  Config:    %HERMES_HOME%                    ║
echo  ║                                              ║
echo  ║  Run "hermes" to start chatting!             ║
echo  ║                                              ║
echo  ║  Switch models anytime with:                 ║
echo  ║    /model gpt-4o                             ║
echo  ║    /model claude-sonnet-4                    ║
echo  ║    /model deepseek-chat                      ║
echo  ║                                              ║
echo  ║  627+ models available via Crazyrouter       ║
echo  ╚══════════════════════════════════════════════╝
echo.

pause
